# Generated by Django 3.1.7 on 2021-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210311_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(max_length=33, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
